// Package docs renders taxonomy/format/: one page per doctype with a fill-in template
// and every vocabulary it uses.
//
// The schema is split across several files so each stays readable, and that split is
// what makes "what does this doctype need?" a multi-file question. These pages resolve
// it, so writing frontmatter is one read. They are generated: edit the schema and
// re-run, and `docs --check` fails while a page is stale.
package docs

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jvanmelckebeke/taxidermist/internal/schema"
	"github.com/jvanmelckebeke/taxidermist/internal/value"
)

// HouseRules is the hand-written file whose text leads the index page's rules.
const HouseRules = "house-rules.md"

func banner(s *schema.Schema) string {
	return "<!-- GENERATED by taxidermist from " + filepath.Base(s.Dir) +
		"/. Do not hand-edit: edit the schema and run `taxidermist docs`. -->"
}

func readmeLink(s *schema.Schema) string {
	if _, err := os.Stat(filepath.Join(s.Dir, "README.md")); err == nil {
		return "[..](../README.md)"
	}
	return "[..](..)"
}

// Pages returns page name (without .md) -> body, including the README index.
func Pages(s *schema.Schema) (map[string]string, error) {
	out := map[string]string{}
	for _, dt := range s.Doctypes() {
		t := s.Types[dt]
		out[t.Slug] = render(s, t)
	}
	idx := []string{
		"# Writing frontmatter, one page per doctype", "", banner(s), "",
		"Each page resolves one `type:`: its obligations, a fill-in template, what to put in " +
			"every field and every vocabulary it uses. Generated from " + readmeLink(s) +
			", which is the schema and the thing to edit.", "",
	}
	for _, dt := range s.Doctypes() {
		idx = append(idx, "- [`"+dt+"`]("+s.Types[dt].Slug+".md)")
	}
	if len(s.Segments) > 0 {
		idx = append(idx, "", "## Folders", "",
			"A folder name directly under these directories, or the filename of a page sitting directly "+
				"there, must be an allowed value. `index.md` and `README.md` there describe the directory itself.", "")
		for _, sg := range s.Segments {
			line := "- `" + sg.Dir + "/<name>`: "
			if sg.Pattern != nil {
				line += "`<name>` matches `" + sg.Pattern.String() + "`."
			} else {
				line += "`<name>` is a value of [`" + sg.Vocabulary + "`](../vocabularies/" + sg.Vocabulary + ".yaml)."
			}
			if sg.Field != "" {
				line += " A file whose `" + sg.Field + ":` names a different value gets a warning."
			}
			idx = append(idx, line)
		}
	}
	idx = append(idx, "", "## What holds on every page", "")
	house, err := os.ReadFile(filepath.Join(s.Dir, HouseRules))
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	if h := strings.TrimSpace(string(house)); h != "" {
		idx = append(idx, h, "")
	}
	idx = append(idx,
		"**A field's `definitions` keys are its allowed values.** There is no second list, so a "+
			"value cannot exist until someone writes down what it means. Prefer an existing one, "+
			"because a near-synonym fragments every filter. If nothing fits, add it to the right file "+
			"under "+readmeLink(s)+" with its one line in the same change, then run `taxidermist docs`. "+
			"`taxidermist check` blocks the commit otherwise.", "",
		"**YAML frontmatter is hand-written and fails silently.** A block that opens and does not "+
			"parse leaves the file invisible to every tool that reads it, while it looks correct on "+
			"disk. An unescaped quote, or a `: ` inside an unquoted scalar, is where it usually breaks.", "")
	out["README"] = strings.Join(idx, "\n")
	return out, nil
}

func valueType(f *schema.Field) string {
	if f == nil || f.Value == "" {
		return "str"
	}
	return f.Value
}

// nested is the key block of an object field or of a list's items, whichever it has.
func nested(f *schema.Field) []*schema.Field {
	return f.Nested()
}

func render(s *schema.Schema, t *schema.Type) string {
	names := append(append([]string(nil), t.Required...), t.Optional...)
	required := map[string]bool{}
	for _, n := range t.Required {
		required[n] = true
	}
	spec := func(name string) *schema.Field {
		if f := t.Resolved[name]; f != nil {
			return f
		}
		return &schema.Field{Name: name}
	}
	vals := func(f *schema.Field) []string {
		seen := map[string]bool{}
		var out []string
		for _, d := range f.Enum() {
			k := d.Key
			if !seen[k] {
				seen[k] = true
				out = append(out, k)
			}
		}
		sort.Strings(out)
		return out
	}

	L := []string{"# Frontmatter for `type: " + t.Doctype + "`", "", banner(s), ""}
	if len(t.Traits) > 0 {
		quoted := make([]string, len(t.Traits))
		for i, tr := range t.Traits {
			quoted[i] = "`" + tr + "`"
		}
		L = append(L, "Composes "+joinAnd(quoted)+", the field bundles in [../traits.yaml](../traits.yaml).", "")
	}

	L = append(L, "## Copy this", "", "```yaml", "---")
	for _, name := range names {
		f, v := spec(name), vals(spec(name))
		tail := ""
		if !required[name] {
			tail = "   # optional"
		}
		sub := nested(f)
		switch {
		case name == "type":
			L = append(L, "type: "+t.Doctype)
		case len(sub) > 0 && f.Value == "object":
			L = append(L, name+":"+tail)
			for _, k := range sub {
				L = append(L, "  "+k.Name+": <"+k.Value+">"+optMark(k))
			}
		case len(sub) > 0:
			L = append(L, name+":"+tail)
			for i, k := range sub {
				lead := "    "
				if i == 0 {
					lead = "  - "
				}
				L = append(L, lead+k.Name+": <"+k.Value+">"+optMark(k))
			}
		case len(v) > 0 && f.Value == "list":
			L = append(L, name+": [<"+strings.Join(v, " | ")+">]"+tail)
		case len(v) > 0:
			L = append(L, name+": <"+strings.Join(v, " | ")+">"+tail)
		case f.Value == "list":
			L = append(L, name+": []"+tail)
		default:
			L = append(L, name+": <"+valueType(f)+">"+tail)
		}
	}
	L = append(L, "---", "```", "")

	for _, c := range t.RequiredWhen {
		var parts []string
		for i, w := range c.When.Keys {
			parts = append(parts, "`"+w+": "+value.Text(c.When.Vals[i])+"`")
		}
		L = append(L, "**`"+c.Field+"` is required only when "+strings.Join(parts, ", ")+".**", "")
	}

	L = append(L, "## What to put in each field", "")
	for _, name := range names {
		f, v := spec(name), vals(spec(name))
		req := "optional"
		if required[name] {
			req = "required"
		}
		L = append(L, "**`"+name+"`** · "+req+" · `"+valueType(f)+"`  ")
		if f.Guidance != "" {
			L = append(L, f.Guidance)
		} else {
			L = append(L, "_No guidance written yet. Add `guidance:` to this field in the schema._")
		}
		if f.Excludes != "" {
			L = append(L, "", "Never repeats `"+f.Excludes+"`. Checked.")
		}
		if sub := nested(f); len(sub) > 0 {
			L = append(L, "")
			for _, k := range sub {
				kreq := "optional"
				if k.Required {
					kreq = "required"
				}
				line := "- `" + k.Name + "` · " + kreq + " · `" + k.Value + "`"
				if k.Guidance != "" {
					line += ": " + k.Guidance
				}
				if k.Reference != "" {
					line += " Any page under [`" + k.Reference + "/`](../../" + k.Reference + "/), checked."
				}
				L = append(L, line)
				for _, d := range k.Enum() {
					line := "  - `" + d.Key + "`: " + d.Means
					if d.Not != "" {
						line += " Not for: " + d.Not
					}
					L = append(L, line)
				}
			}
		} else if f.Reference != "" {
			L = append(L, "", "Values: any page under [`"+f.Reference+"/`](../../"+f.Reference+"/), "+
				"by its filename without `.md`. Checked, so a name that resolves to no page is a fault.")
		} else if len(v) > 0 {
			ticked := make([]string, len(v))
			for i, x := range v {
				ticked[i] = "`" + x + "`"
			}
			end := "."
			if hasMeanings(f.Enum()) {
				end = ", defined below."
			}
			L = append(L, "", "Values: "+strings.Join(ticked, " · ")+end)
		}
		L = append(L, "")
	}

	wrote := false
	for _, name := range names {
		f := spec(name)
		v, enum := vals(f), f.Enum()
		if len(v) == 0 || !hasMeanings(enum) {
			continue
		}
		if !wrote {
			L = append(L, "## What the values mean", "")
			wrote = true
		}
		L = append(L, "### `"+name+"`", "")
		grouped := false
		if f.Vocabulary != "" {
			L = append(L, "Shared vocabulary from [../vocabularies/"+f.Vocabulary+".yaml](../vocabularies/"+f.Vocabulary+".yaml).", "")
			for _, d := range enum {
				grouped = grouped || d.Group != ""
			}
		}
		nots := false
		for _, d := range enum {
			nots = nots || d.Not != ""
		}
		head, rule := "| value |", "|---|"
		if grouped {
			head, rule = head+" group |", rule+"---|"
		}
		head, rule = head+" means |", rule+"---|"
		if nots {
			head, rule = head+" not for |", rule+"---|"
		}
		L = append(L, head, rule)
		for _, x := range v {
			d := lookup(enum, x)
			row := "| `" + x + "` |"
			if grouped {
				row += " " + d.Group + " |"
			}
			row += " " + cell(d.Means) + " |"
			if nots {
				row += " " + cell(d.Not) + " |"
			}
			L = append(L, row)
		}
		L = append(L, "")
	}

	L = append(L, "## Adding a value", "",
		"A field's `definitions` keys **are** its allowed values, so a value cannot exist until "+
			"someone writes down what it means. Prefer an existing one, because a near-synonym "+
			"fragments every filter. If nothing fits, add it to the right file under "+readmeLink(s)+
			" with its one line, in the same change that uses it. `taxidermist check` blocks the "+
			"commit otherwise.", "")
	return strings.Join(L, "\n")
}

func optMark(f *schema.Field) string {
	if f.Required {
		return ""
	}
	return "   # optional"
}

func hasMeanings(enum []schema.Def) bool {
	for _, d := range enum {
		if d.Means != "" {
			return true
		}
	}
	return false
}

func lookup(enum []schema.Def, key string) schema.Def {
	for _, d := range enum {
		if d.Key == key {
			return d
		}
	}
	return schema.Def{}
}

// cell keeps a definition inside its table cell.
func cell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", `\|`), "\n", " ")
}

func joinAnd(xs []string) string {
	switch len(xs) {
	case 0:
		return ""
	case 1:
		return xs[0]
	}
	return strings.Join(xs[:len(xs)-1], ", ") + " and " + xs[len(xs)-1]
}

// Sync writes the pages, or with check set reports the stale ones and writes nothing.
// A page on disk that no doctype generates is stale too, and is deleted on a write.
func Sync(s *schema.Schema, check bool) (stale []string, written, total int, err error) {
	out := filepath.Join(s.Dir, "format")
	pages, err := Pages(s)
	if err != nil {
		return nil, 0, 0, err
	}
	if !check {
		if err := os.MkdirAll(out, 0o755); err != nil {
			return nil, 0, 0, err
		}
	}
	names := make([]string, 0, len(pages))
	for n := range pages {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		p := filepath.Join(out, name+".md")
		body := strings.TrimRight(pages[name], "\n") + "\n"
		if cur, err := os.ReadFile(p); err == nil && string(cur) == body {
			continue
		}
		if check {
			stale = append(stale, p)
			continue
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			return nil, 0, 0, err
		}
		written++
	}
	existing, _ := filepath.Glob(filepath.Join(out, "*.md"))
	sort.Strings(existing)
	for _, p := range existing {
		if _, ok := pages[strings.TrimSuffix(filepath.Base(p), ".md")]; ok {
			continue
		}
		if check {
			stale = append(stale, p)
		} else if err := os.Remove(p); err != nil {
			return nil, 0, 0, err
		}
	}
	return stale, written, len(pages), nil
}
